os: osx

before_install:
  # Download and install a minimal TeX Live, based on
  # https://github.com/latex3/latex3/blob/master/support/texlive.sh.
  - wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
  - tar -xzf install-tl-unx.tar.gz
  - cd install-tl-20*
  - echo -e "selected_scheme scheme-minimal\nTEXDIR /usr/local/texlive\noption_doc 0\noption_src 0" > texlive.profile
  - sudo ./install-tl --profile=texlive.profile
  - cd ..
  - PATH=$PATH:/usr/local/texlive/bin/x86_64-darwin
  - sudo tlmgr install
    fontspec
    geometry
    gillius
    graphics
    libertine
    oberdiek
    pgf
    url
    xcolor
    xetex
  - ln -s /usr/local/texlive/texmf-dist/fonts/opentype/public/libertine ~/Library/Fonts/libertine
  - ln -s /usr/local/texlive/texmf-dist/fonts/opentype/arkandis/gillius ~/Library/Fonts/gillius

  # Get the cross-and-crescent LaTeX package.
  - wget https://github.com/lcamichigan/cross-and-crescent/releases/download/v1.3/cross-and-crescent.sty

  # Install Ghostscript using Homebrew <https://brew.sh>.
  - brew install ghostscript

script:
  - python --version
  - python init.py
  - python make_notes.py
  - gs -dBATCH -dNOPAUSE -sDEVICE=pdfwrite -sOutputFile=Notes.pdf notes/*.pdf
